Name:           ros-kinetic-industrial-core
Version:        0.6.0
Release:        0%{?dist}
Summary:        ROS industrial_core package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/industrial_core
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-industrial-deprecated
Requires:       ros-kinetic-industrial-msgs
Requires:       ros-kinetic-industrial-robot-client
Requires:       ros-kinetic-industrial-robot-simulator
Requires:       ros-kinetic-industrial-trajectory-filters
Requires:       ros-kinetic-industrial-utils
Requires:       ros-kinetic-simple-message
BuildRequires:  ros-kinetic-catkin

%description
ROS-Industrial core stack contains packages and libraries for supporing
industrial systems

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Jan 16 2017 Shaun Edwards <sedwards@swri.org> - 0.6.0-0
- Autogenerated by Bloom

